# Generated by Django 4.1.7 on 2023-03-31 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('fruits', 'fruits')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('date_posted', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=20, max_length=10)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=20, max_length=10)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=20, max_length=10)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=20, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, max_length=10)),
                ('category', models.ManyToManyField(to='caloriesapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ManyToManyField(blank=True, to='caloriesapp.customer')),
                ('fooditem', models.ManyToManyField(to='caloriesapp.fooditem')),
            ],
        ),
    ]
